pluginManagement {
    repositories {
        maven { url = 'https://repo.huaweicloud.com/repository/maven/' }
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = 'https://maven.aliyun.com/repository/google' }
        maven { url = 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url = 'https://maven.aliyun.com/repository/central' }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = 'https://repo.huaweicloud.com/repository/maven/' }
        google()
        mavenCentral()
        maven { url = 'https://maven.aliyun.com/repository/google' }
        maven { url = 'https://maven.aliyun.com/repository/central' }
    }
}

rootProject.name = "MiBackscreen"
include(":app")
